# Generated by Django 5.2.7 on 2025-10-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budget_tracker.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
