# Generated by Django 5.2.7 on 2025-10-21 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0002_transaction_budget_alter_budget_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
