# Generated by Django 5.2.7 on 2025-10-22 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0003_alter_budget_end_alter_budget_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Use the format <em>YYYY-MM-DD</em> for dates'),
        ),
    ]
