# Generated by Django 5.2.7 on 2025-10-22 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0004_alter_budget_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='target',
            new_name='goal',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('interest', 'Interest'), ('food', 'Food'), ('rent', 'Rent'), ('debt', 'Debt'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(help_text='Provide a short descriptor', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Use the format <em>YYYY-MM-DD</em> for dates'),
        ),
    ]
