# Generated by Django 5.2.7 on 2025-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0005_rename_target_budget_goal_transaction_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter in profit or expense', max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True),
        ),
    ]
