# Generated by Django 5.2.8 on 2025-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0006_alter_transaction_amount_alter_transaction_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
