# Generated by Django 5.2.7 on 2025-11-14 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField()),
                ('account_type', models.CharField(choices=[('CHECKING', 'CHECKING'), ('SAVINGS', 'SAVINGS'), ('BUSINESS', 'BUSINESS')])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('firstname', models.CharField()),
                ('lastname', models.CharField()),
                ('phone', models.CharField()),
                ('dateOfBirth', models.DateField()),
                ('role', models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN'), ('BANKER', 'BANKER')])),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAWAL', 'WITHDRAWAL'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('PURCHASE', 'PURCHASE'), ('REFUND', 'REFUND'), ('FEE', 'FEE')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.CharField(blank=True)),
                ('merchant_name', models.CharField(blank=True)),
                ('merchant_category', models.CharField(blank=True)),
                ('location', models.CharField(blank=True)),
                ('ipAddress', models.CharField(blank=True)),
                ('deviceFingerprint', models.CharField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('FLAGGED', 'FLAGGED'), ('BLOCKED', 'BLOCKED'), ('UNDER_REVIEW', 'UNDER_REVIEW')], default='PENDING')),
                ('fraud_score', models.IntegerField(blank=True)),
                ('fraud_reason', models.CharField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureBank_Hub.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureBank_Hub.user'),
        ),
    ]
