# Generated by Django 5.2.7 on 2025-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureBank_Hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='fraud_status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deviceFingerprint',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_reason',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ipAddress',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
