# Generated by Django 5.2.7 on 2025-11-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureBank_Hub', '0002_rename_status_transaction_fraud_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transact_type',
            new_name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
